apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workout-gateway
  name: workout-gateway
spec:
  selector:
    matchLabels:
      app: workout-gateway
  template:
    metadata:
      labels:
        app: workout-gateway
    spec:
      containers:
      - env:
        - name: RUN_CONTROLLER_URL
          value: http://run-controller:8080
        image: docker.io/borgessc/work_gtw:v1
        imagePullPolicy: Always
        name: workout-gateway 
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
